//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockShop.StockShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Income = new HashSet<Income>();
            this.Outcome = new HashSet<Outcome>();
        }
    
        public int id { get; set; }
        public int id_position { get; set; }
        public string fio { get; set; }
        public string address { get; set; }
        public string passport { get; set; }
        public string number_phone { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<Income> Income { get; set; }
        public virtual ICollection<Outcome> Outcome { get; set; }
    }
}
