//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockShop.StockShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public Income()
        {
            this.Log_income = new HashSet<Log_income>();
        }
    
        public int id { get; set; }
        public int id_employee { get; set; }
        public string name_income { get; set; }
        public System.DateTime date_order_income { get; set; }
        public System.DateTime data_income { get; set; }
        public double price_income { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Log_income> Log_income { get; set; }
    }
}
