//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockShop.StockShopDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_outcome
    {
        public int id { get; set; }
        public int id_outcome { get; set; }
        public int id_product { get; set; }
        public int count_outcome_product { get; set; }
    
        public virtual Outcome Outcome { get; set; }
        public virtual Product Product { get; set; }
    }
}
