//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockShop.StockShopModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Income = new HashSet<Income>();
            this.Outcome = new HashSet<Outcome>();
        }
    
        public int id { get; set; }
        public int id_position { get; set; }
        public string fio { get; set; }
        public string address { get; set; }
        public string passport { get; set; }
        public string number_phone { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual ICollection<Income> Income { get; set; }
        public virtual ICollection<Outcome> Outcome { get; set; }
    }
}
