//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockShop.StockShopModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_outcome
    {
        public int id { get; set; }
        public int id_outcome { get; set; }
        public int id_product { get; set; }
        public int count_outcome_product { get; set; }
    
        public virtual Outcome Outcome { get; set; }
        public virtual Product Product { get; set; }
    }
}
